on: 
  push:
    branches:
    - develop
    - docs
  release:
    types: [published]
name: Build and Test
jobs:
  buildWindows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Build Command Line Utilities and Library
      run: |
        cd Utils\build
        cmake .
        cmake --build .
        
    - name: Test Command Line Utilities
      run: |
        cd Utils\build
        .\Debug\Cli_Tests.exe

    - name: Test Dynamic Library using C
      run: |
        cd Utils\build
        .\Debug\C_Tests.exe

    - name: Test Dynamic Library using C++
      run: |
        cd Utils\build
        .\Debug\Cpp_Tests.exe
        
    - name: Test Static Library using C
      run: |
        cd Utils\build
        .\Debug\C_LibTests.exe

    - name: Test Static Library using C++
      run: |
        cd Utils\build
        .\Debug\Cpp_LibTests.exe
        
    - name: Build and Test C# Libraries
      run: | 
        dotnet test
        
    - name: Test Version
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils\build\Debug
        $cmdOutput = &".\datfile.exe" -v
        $cmdVersion = $cmdOutput.Substring(12)
        $relVersion =  "${{ github.event.release.name }}"
        echo $cmdVersion
        echo $relVersion
        if ($cmdVersion -ne $relVersion) { exit 1 }
        
    - name: Package Utilities
      run: |
        cd Utils\package
        .\utils.cmd
        
    - name: Upload Artifacts
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Utils/package/Utils-win-x64-${{ github.event.release.name }}.zip

  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Install .NET 6 SDK
      run: |
        sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
      
    - name: Build Command Line Utilities and Library
      run: |
        cd Utils/build
        cmake .
        cmake --build .
        
    - name: Test Command Line Utilities
      run: |
        cd Utils/build
        ./Debug/Cli_Tests

    - name: Test Dynamic Library using C
      run: |
        cd Utils/build
        ./Debug/C_Tests

    - name: Test Dynamic Library using C++
      run: |
        cd Utils/build
        ./Debug/Cpp_Tests
        
    - name: Test Static Library using C
      run: |
        cd Utils/build
        ./Debug/C_LibTests

    - name: Test Static Library using C++
      run: |
        cd Utils/build
        ./Debug/Cpp_LibTests
        
    - name: Build and Test C# Libraries
      run: | 
        dotnet test

    - name: Test Version
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils/build/Debug
        cmdOutput=$(./DatFile -v)
        cmdVersion=${cmdOutput:8}
        relVersion="${{ github.event.release.name }}"
        echo $cmdVersion
        echo $relVersion
        if [ ! "$cmdVersion" == "$relVersion" ]; then exit 1; fi
        
    - name: Package Utilities
      run: |
        cd Utils/package
        ./utils.sh
        
    - name: Upload Artifacts
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Utils/package/Utils-linux-x64-${{ github.event.release.name }}.tgz

        
        
