on: 
  push:
    branches:
    - develop
  release:
    types: [published]
name: Build and Test
jobs:
  buildWindows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Build Command Line Utilities and Library
      run: |
        cd Utils\build
        cmake .
        cmake --build .
        
    - name: Test Command Line Utilities
      run: |
        cd Utils\build
        .\Debug\Cli_Tests.exe

    - name: Test Library using C
      run: |
        cd Utils\build
        .\Debug\C_Tests.exe

    - name: Test Library using C++
      run: |
        cd Utils\build
        .\Debug\Cpp_Tests.exe
        
    - name: Test Version
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils\build\Debug
        $cmdOutput = &".\datfile.exe" -v
        $cmdVersion = "v" + $cmdOutput.Substring(12)
        $relVersion =  ${{ github.event.release.name }}
        echo $cmdVersion
        echo $relVersion
        if ($cmdVersion -ne $relVersion) { exit 1 }
        
    - name: Package Utilities
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils\build
        mkdir artifacts
        Compress-Archive -Path ".\Debug\DatFile.exe", ".\Debug\ImmFile.exe", "..\..\LICENSE", "..\..\doc\datfile.md", "..\..\doc\immfile.md" -DestinationPath "artifacts\Utils-win-x64-${{ github.event.release.name }}.zip"
        
    - name: Upload Artifacts
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Utils/build/artifacts/artifacts/Utils-win-x64-${{ github.event.release.name }}.zip

        
