on: 
  push:
    branches:
    - develop
  release:
    types: [published]
name: Build and Test
jobs:
  buildWindows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Build Command Line Utilities and Library
      run: |
        cd Utils\build
        cmake .
        cmake --build .
        
    - name: Test Command Line Utilities
      run: |
        cd Utils\build
        .\Debug\Cli_Tests.exe

    - name: Test Dynamic Library using C
      run: |
        cd Utils\build
        .\Debug\C_Tests.exe

    - name: Test Dynamic Library using C++
      run: |
        cd Utils\build
        .\Debug\Cpp_Tests.exe
        
    - name: Test Static Library using C
      run: |
        cd Utils\build
        .\Debug\C_LibTests.exe

    - name: Test Static Library using C++
      run: |
        cd Utils\build
        .\Debug\Cpp_LibTests.exe
        
    - name: Build and Test C# Libraries
      run: | 
        dotnet test
        
    - name: Test Version
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils\build\Debug
        $cmdOutput = &".\datfile.exe" -v
        $cmdVersion = $cmdOutput.Substring(12)
        $relVersion =  "${{ github.event.release.name }}"
        echo $cmdVersion
        echo $relVersion
        if ($cmdVersion -ne $relVersion) { exit 1 }
        
    - name: Package Utilities
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils\build
        mkdir artifacts
        cd artifacts
        mkdir utils
        copy ..\Debug\DatFile.exe utils
        copy ..\Debug\ImmFile.exe utils
        copy ..\..\..\LICENSE utils
        copy ..\..\..\rapidyaml_LICENSE.txt utils
        copy ..\..\..\doc\utilities\datfile.md utils
        copy ..\..\..\doc\utilities\immfile.md utils
        Compress-Archive -Path ".\utils\*" -DestinationPath "Utils-win-x64-${{ github.event.release.name }}.zip"
        mkdir lib
        mkdir lib\lib
        copy ..\Debug\LibFuryUtils.lib lib\lib
        copy ..\Debug\FuryUtils.dll lib\lib
        copy ..\Debug\FuryUtils.lib lib\lib
        copy ..\..\..\UtilsDotNet\bin\Debug\net6.0\carbon14.FuryStudio.Utils.dll lib\lib
        mkdir lib\include
        copy ..\..\include\* lib\include
        mkdir lib\doc
        mkdir lib\doc\c
        copy ..\..\..\doc\lib\c\* lib\doc\c
        mkdir lib\doc\cpp
        copy ..\..\..\doc\lib\cpp\* lib\doc\cpp
        mkdir lib\doc\cs
        copy ..\..\..\doc\lib\cs\* lib\doc\cs
        mkdir lib\samples
        mkdir lib\samples\c
        copy ..\..\C_Samples\*.c lib\samples\c
        del lib\samples\c\main.c
        mkdir lib\samples\cpp
        copy ..\..\Cpp_Samples\*.cpp lib\samples\cpp
        del lib\samples\cpp\main.cpp
        mkdir lib\samples\cs
        copy ..\..\..\CS_Samples\*.cs lib\samples\cs
        del lib\samples\cs\Program.cs
        del lib\samples\cs\TestHelpers.cs
        copy ..\..\..\LICENSE lib
        copy ..\..\..\rapidyaml_LICENSE.txt utils
        Compress-Archive -Path ".\lib\*" -DestinationPath "Lib-win-x64-${{ github.event.release.name }}.zip"
        mkdir testassets
        copy ..\..\..\testassets\* testassets
        Compress-Archive -Path ".\testassets\*" -DestinationPath "TestAssets-win-x64-${{ github.event.release.name }}.zip"
        
    - name: Upload Artifacts
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Utils/build/artifacts/Utils-win-x64-${{ github.event.release.name }}.zip
          Utils/build/artifacts/Lib-win-x64-${{ github.event.release.name }}.zip
          Utils/build/artifacts/TestAssets-win-x64-${{ github.event.release.name }}.zip

  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Build Command Line Utilities and Library
      run: |
        cd Utils/build
        cmake .
        cmake --build .
        
    - name: Test Command Line Utilities
      run: |
        cd Utils/build
        ./Debug/Cli_Tests

    - name: Test Dynamic Library using C
      run: |
        cd Utils/build
        ./Debug/C_Tests

    - name: Test Dynamic Library using C++
      run: |
        cd Utils/build
        ./Debug/Cpp_Tests
        
    - name: Test Static Library using C
      run: |
        cd Utils/build
        ./Debug/C_LibTests

    - name: Test Static Library using C++
      run: |
        cd Utils/build
        ./Debug/Cpp_LibTests
        
    - name: Build and Test C# Libraries
      run: | 
        dotnet test

    - name: Test Version
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils/build/Debug
        cmdOutput=$(./DatFile -v)
        cmdVersion=${cmdOutput:8}
        relVersion="${{ github.event.release.name }}"
        echo $cmdVersion
        echo $relVersion
        if [ ! "$cmdVersion" == "$relVersion" ]; then exit 1; fi
        
    - name: Package Utilities
      if: ${{ github.event_name == 'release' }}
      run: |
        cd Utils/build
        mkdir artifacts
        cd artifacts
        mkdir utils
        cp ../Debug/DatFile utils
        cp ../Debug/ImmFile utils
        chmod 775 utils/*
        cp ../../../LICENSE utils
        cp ../../../rapidyaml_LICENSE.txt utils
        cp ../../../doc/utilities/datfile.md utils
        cp ../../../doc/utilities/immfile.md utils
        tar -cvzf "Utils-linux-x64-${{ github.event.release.name }}.tgz" utils
        mkdir lib
        mkdir lib/lib
        cp ../Debug/libFuryUtils.so lib/lib
        cp ../Debug/libFuryUtils.a lib/lib
        cp ../../../UtilsDotNet/bin/Debug/net6.0/carbon14.FuryStudio.Utils.dll lib/lib
        mkdir lib/include
        cp ../../include/* lib/include
        mkdir lib/doc
        mkdir lib/doc/c
        cp ../../../doc/lib/c/* lib/doc/c
        mkdir lib/doc/cpp
        cp ../../../doc/lib/cpp/* lib/doc/cpp
        mkdir lib/doc/cs
        cp ../../../doc/lib/cs/* lib/doc/cs
        mkdir lib/samples
        mkdir lib/samples/c
        cp ../../C_Samples/*.c lib/samples/c
        rm lib/samples/c/main.c
        mkdir lib/samples/cpp
        cp ../../Cpp_Samples/*.cpp lib/samples/cpp
        rm lib/samples/cpp/main.cpp
        mkdir lib/samples/cs
        cp ../../../CS_Samples/*.cs lib/samples/cs
        rm lib/samples/cs/Program.cs
        rm lib/samples/cs/TestHelpers.cs
        cp ../../../LICENSE lib
        cp ../../../rapidyaml_LICENSE.txt utils
        tar -cvzf "Lib-linux-x64-${{ github.event.release.name }}.tgz" lib
        mkdir testassets
        cp ../../../testassets/* testassets
        tar -cvzf "TestAssets-linux-x64-${{ github.event.release.name }}.tgz" testassets
        
    - name: Upload Artifacts
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Utils/build/artifacts/Utils-linux-x64-${{ github.event.release.name }}.tgz
          Utils/build/artifacts/Lib-linux-x64-${{ github.event.release.name }}.tgz
          Utils/build/artifacts/TestAssets-linux-x64-${{ github.event.release.name }}.tgz

        
        
