on:
  push:
name: Build and Test
jobs:
  buildWindows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Checkout Submodules
      run: git submodule update --init
      
    - name: Build cli and library
      run: |
        cd Utils\build
        cmake .
        cmake --build .
        
    - name: Test cli
      run: .\Debug\Cli_Tests.exe